#!/usr/bin/env bash
# Requires python-moneywagon
#   pip install moneywagon

# usage:
#  ./ccurrency fiat


fiat=$1
check="${@:2}"

declare -A coins
coins=(
    ["btc"]=""
    ["ltc"]="Ł"
    ["eth"]="Ξ"
)

for i in ${check}; do
    price=$(moneywagon current-price ${i} $fiat)
    printf "${coins[$i]} $(echo $price | awk '{printf "%\047.2f", $1}') "
done

printf "\n"
